export const defaultState = {
    init: false,
    start: false,
    difficulty: 'easy',
    level: 1,
    coins: 400,
    answer: 'ICE',
    previousAnswer: '',
    firstEmptySlotNo: 0,
    emptySlot: [],
    default: [],
    guessed: true,
    won: false,
    fastGuessData: [],
    guessedValues: [],
    setDisableHole: [],
    setGuessUpdate: false,
    unPressable: [],
    congratulation: false,
}